version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: .build/sprk
          destination: binaries
